---
apiVersion: tsdb.opendcs.org/v1
kind: OpenDcsDatabase
metadata:
  name: local-database
spec:
  schemaVersion: ghcr.io/opendcs/compdepends:main-nightly
  databaseSecret: test-secret
  placeholders: {
    NUM_TS_TABLES: "1",
    NUM_TEXT_TABLES: "1",
  }