name: controller docker image
inputs:
  exec:
    type: string
    description: controller executable name
    required: true
  push:
    type: boolean
    required: true
    description: whether or
    default: false
outputs: {}
  
runs:
  using: "composite"
  steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ghcr.io/opendcs/k8s/${{inputs.exec}}-controller
        tags: |
          type=sha,format=long
          type=ref,event=tag
          type=ref,event=branch
    - uses: docker/build-push-action@v6
      id: build-and-push
      with:
        push: ${{ inputs.push }}
        tags: ${{ steps.meta.outputs.tags }}
        target: ${{inputs.exec}}
    - name: Sign the container image
      shell: bash
      if: inputs.push == true
      env:
        DIGEST: ${{ steps.build-and-push.outputs.digest }}
        TAGS: ${{ steps.meta.outputs.tags }}
      run: |
        images=""
        for tag in ${TAGS}; do
          images+="${tag}@${DIGEST} "
        done
        cosign sign --yes ${images}