name: Operator 
on:
  pull_request:
    branches:
      - "main"
    types: [opened, synchronize, reopened]
  push:
    branches:
      - "main"

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Clean up disk space, so we don't run out.
        run: |
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /usr/local/lib/android
          sudo rm -rf /opt/ghc
      - uses: actions/checkout@v4.1.1
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - run: cargo test
  docker-images:
    runs-on: ubuntu-latest
    steps:
      - name: Clean up disk space, so we don't run out.
        run: |
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /usr/local/lib/android
          sudo rm -rf /opt/ghc
      - uses: actions/checkout@v4.1.1
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: k8s/lrgs-controller
          tags: type=sha,format=long
      - uses: docker/build-push-action@v6
        id: build-and-push
        with:
          platforms: linux/amd64,linux/arm64/v8
          push: true
          tags: ${{ steps.meta.outputs.tags }}