---
name: Tagged Release
on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'
      - '[0-9]+.[0-9]+.[0-9]+-RC[0-9]+'
  release:
    types: [published,prereleased]
jobs:
  release-from-tag:
    permissions:
      id-token: write
      contents: write
      packages: write
    uses: ./.github/workflows/release.yml
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
    with:
      branch: ${{github.ref_name}}
      nightly: false